const actionTypes = {
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USERS: 'GET_USERS',
  GET_USER_SUCCESSFUL: 'GET_USER_SUCCESSFUL',
  GET_USER_FAILED: 'GET_USER_FAILED'
}

export default actionTypes